### ISSUE TITLE
[자료팀] 내 보관함에 문서 추가 기능

### ISSUE THREAD

**Issue by cinxdy** [KUBIC-HGU/TIBigdataFE#5]
안녕하세요. Data팀입니다! 내 보관함 기능 다음과 같이 추가해주시면 될 것 같습니다!

1. 내 보관함 collection 내에 추가
2. 데이터 구조는 논의해보면 좋을 것 같은데 우선 제가 생각하는 구조는
{
 "email": "21800409@handong.edu" (string),
 "idList": ["id1", "id2", "id3" ] (list),
 "keyword": ["keyword1", "keyword2", "keyword3" ] (list),
 "title": ["title1", "title2", "title3" ] (list),
}
입니다. 이 부분은 논의 후에 결정하면 될 것 같습니다.
3. 완료 후에 해당 부분 reply로 reference 달아주시면 감사하겠습니다!!!

**Comment by cinxdy** [comment]
{
"email": "21800409@handong.edu" (string),
“keywordlist” : [
   [ “keyword” : keyword1,
   “docList” : [id1, id2, id3],
   "titleList": [title1, title2, title3],

   [ “keyword” : keyword2,
   “docList” : [id1, id2, id3],
   "titleList": [title1, title2, title3],
]
}로 수정됨

**Comment by lamb0711** [comment]
Date 값을 함께 저장 
{
"email": "21800409@handong.edu" (string),
“keywordlist” : [ 
   {
  “keyword” : keyword1,
   “docList” : [id1, id2, id3],
  "savedDate": 2021.07.08 4:23:01 (Date type),
   },
   {
  “keyword” : keyword2,
   “docList” : [id1, id2, id3],
  "savedDate": 2021.07.08 4:23:01 (Date type),
   },
],
}
