### ISSUE TITLE
회원가입 페이지 약관 동의 부분

### ISSUE THREAD

**Issue by cinxdy** [KUBIC-HGU/TIBigdataFE#91]
![image](https://user-images.githubusercontent.com/41468794/161731687-c3e6ce94-0416-4219-ab2d-a02d0018df2d.png)

안녕하세요 회원가입 약관 동의시 하나는 영어이고 하나는 한국어인 것을 발견했습니다
 수정 부탁드립니다!!

**Comment by zackcglee** [comment]
ngx-translate에서 동일한 이름의 번역태그가 존재할때 생기는 버그입니다.
보실 수 있는 format의 영어 형태가 발생하면 동일 한 버그이므로 ko.json과 en.json파일에서 해당 태그와 동일한 이름 또는 번역의 태그를 수정하고 일부조정하여 해결이 가능합니다.

해당 문제는 해결되었습니다.
